AWSTemplateFormatVersion: 2010-09-09
Description: A simple CloudFormation template
Resources:
    Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: aicore-cloudformation-demo-bucket-get-data # use your own unique name
    GetDataLambda:
        Type: AWS::Lambda::Function
        Properties: 
          Runtime: python3.8
          Code: 
            ZipFile: |
              def lambda_handler(event, context):
                print('hello world')
          FunctionName: LambdaGetData
          Handler: index.lambda_handler
          Role: arn:aws:iam::251926666850:role/gammaDemoS3Write
    LambdaTriggerRule:
        Type: AWS::Events::Rule
        Properties: 
          ScheduleExpression: rate(1 minutes)
          State: ENABLED
          Targets:
            - Arn: !GetAtt GetDataLambda.Arn
              Id: MyRuleID
