AWSTemplateFormatVersion: 2010-09-09
Description: A simple CloudFormation template
Resources:
    Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: aicore-cloudformation-get-data-demo-bucket # use your own unique name
    GetDataLambda:
        Type: AWS::Lambda::Function
        Properties:
            Runtime: python3.8
            Role: arn:aws:iam::251926666850:role/gammaDemoS3Write
            Handler: index.lambda_handler
            Code: 
                ZipFile: |
                    import os
                    BUCKET = os.environ['BUCKET']

                    def lambda_handler(event, context):
                        print("hello world")
                        return {"statusCode": 200, "body": "hi"}
            Environment:
                Variables:
                    BUCKET: !Ref Bucket
    LambdaTriggerRule:
        Type: AWS::Events::Rule
        Properties:
            ScheduleExpression: rate(1 minute)
            Name: GetDataEveryMinute
            State: ENABLED
            Targets:
                - Arn: !GetAtt GetDataLambda.Arn
                  Id: lambda-get-data