version: '2.2'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  python:
    depends_on:
      - database
    build: .

